use_frameworks!

target 'JSBinding_Example' do
  pod 'JSBinding', :path => '../'

  target 'JSBinding_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
